import os
import sqlite3
import psycopg2


# ==============================
# SQLite：目前電腦裡的資料
# ==============================

BASE_DIR = os.path.dirname(
    os.path.dirname(
        os.path.abspath(__file__)
    )
)

SQLITE_DATABASE = os.path.join(
    BASE_DIR,
    "database",
    "qinxiang_store.db"
)


# ==============================
# PostgreSQL：Render 雲端資料庫
# ==============================

DATABASE_URL = os.environ.get("DATABASE_URL")


if not DATABASE_URL:

    raise RuntimeError(
        "找不到 DATABASE_URL，請先設定 Render PostgreSQL 的連線網址。"
    )


# ==============================
# 連接 SQLite
# ==============================

sqlite_conn = sqlite3.connect(
    SQLITE_DATABASE
)

sqlite_cursor = sqlite_conn.cursor()


# ==============================
# 取得商品資料
# ==============================

sqlite_cursor.execute("""
SELECT
    id,
    name,
    barcode,
    price,
    fridge_max,
    fridge_now,
    display_order,
    restock_threshold
FROM products
ORDER BY id
""")

products = sqlite_cursor.fetchall()


print("================================")
print("開始搬移商品資料")
print("================================")

print(f"目前 SQLite 商品數量：{len(products)}")


# ==============================
# 連接 PostgreSQL
# ==============================

pg_conn = psycopg2.connect(
    DATABASE_URL
)

pg_cursor = pg_conn.cursor()


# ==============================
# 建立 products 表
# ==============================

pg_cursor.execute("""
CREATE TABLE IF NOT EXISTS products (

    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name TEXT NOT NULL,

    barcode TEXT,

    price INTEGER NOT NULL DEFAULT 0,

    fridge_max INTEGER NOT NULL DEFAULT 0,

    fridge_now INTEGER NOT NULL DEFAULT 0,

    display_order INTEGER NOT NULL DEFAULT 0,

    restock_threshold INTEGER NOT NULL DEFAULT 0

)
""")


# ==============================
# 清除目前 PostgreSQL 的商品
# ==============================

pg_cursor.execute("""
DELETE FROM products
""")


# ==============================
# 搬移商品
# ==============================

for product in products:

    pg_cursor.execute("""
    INSERT INTO products (
        id,
        name,
        barcode,
        price,
        fridge_max,
        fridge_now,
        display_order,
        restock_threshold
    )

    VALUES (
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s
    )
    """, product)


# ==============================
# 修正 PostgreSQL ID 序號
# ==============================

pg_cursor.execute("""
SELECT setval(
    pg_get_serial_sequence('products', 'id'),
    COALESCE(
        (SELECT MAX(id) FROM products),
        1
    ),
    true
)
""")


# ==============================
# 完成
# ==============================

pg_conn.commit()


print("================================")
print("✅ 商品資料搬移完成")
print("================================")

pg_cursor.execute("""
SELECT COUNT(*)
FROM products
""")

count = pg_cursor.fetchone()[0]

print(f"PostgreSQL 商品數量：{count}")


# ==============================
# 關閉連線
# ==============================

pg_cursor.close()
pg_conn.close()

sqlite_cursor.close()
sqlite_conn.close()

print("================================")
print("請確認兩邊商品數量相同")
print("================================")